In [117]:
import numpy as np
import os
import sys
import glob

#------Input the CSV file (containing the sudoku) as a list-----0 refers to an empty cell-----
# the file should just be a collection of numbers as they appear in the sudoku puzzle

import csv
inp = list(csv.reader(open('inputmedium.csv')))
itnum = 10 ### number of times the algorithm runs on the puzzle. Can increase this if the parts of the puzzle remain unsolved
inp1 = []
for i in inp:
    i = [int(k) for k in i] 
    inp1.append(i)
 
for x in inp1:
    print(x)  ## print rows from input sudoku


[0, 9, 0, 0, 2, 0, 0, 5, 1]
[0, 1, 0, 0, 5, 0, 6, 0, 3]
[0, 5, 0, 0, 0, 0, 4, 0, 0]
[5, 3, 0, 9, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 1, 0, 0, 5]
[6, 0, 0, 0, 7, 5, 1, 0, 8]
[1, 0, 0, 4, 0, 0, 0, 6, 7]
[3, 0, 0, 0, 1, 0, 0, 2, 0]
[0, 0, 0, 0, 8, 7, 0, 0, 0]


In [118]:
#print(inp1[:3,:3])  ## inp1[:,:3] means consider all the arrays, but only the first 3 elements in each. :3,:3 means consider 
#the first 3 elements of the first 3 arrays only.
inp1 = np.array(inp1) 

nonzero = [] ### this lists the number of non-zero digits present in each 3 x 3 block of the input sudoku. Blocks follow the order: left to right and top to bottom
#print(inp1[:3,:3])
#np.count_nonzero(inp1[:3,:3])
nonzero.append(np.count_nonzero(inp1[:3,:3]))
#print(nonzero)

#print(inp1[:3,3:6])
np.count_nonzero(inp1[:3,3:6])
nonzero.append(np.count_nonzero(inp1[:3,3:6]))
#print(nonzero)

#print(inp1[:3,6:9])
np.count_nonzero(inp1[:3,6:9])
nonzero.append(np.count_nonzero(inp1[:3,6:9]))
#print(nonzero)

#print(inp1[3:6,:3])
np.count_nonzero(inp1[3:6,:3])
nonzero.append(np.count_nonzero(inp1[3:6,:3]))
#print(nonzero)

#print(inp1[3:6,3:6])
np.count_nonzero(inp1[3:6,3:6])
#print(np.count_nonzero(inp1[3:6,3:6]))
nonzero.append(np.count_nonzero(inp1[3:6,3:6]))
#print(nonzero)

#print(inp1[3:6,6:9])
np.count_nonzero(inp1[3:6,6:9])
nonzero.append(np.count_nonzero(inp1[3:6,6:9]))
#print(nonzero)

#print(inp1[6:9,:3])
np.count_nonzero(inp1[6:9,:3])
nonzero.append(np.count_nonzero(inp1[6:9,:3]))
#print(nonzero)

#print(inp1[6:9,3:6])
np.count_nonzero(inp1[6:9,3:6])
nonzero.append(np.count_nonzero(inp1[6:9,3:6]))
#print(nonzero)

#print(inp1[6:9,6:9])
np.count_nonzero(inp1[6:9,6:9])
nonzero.append(np.count_nonzero(inp1[6:9,6:9]))
print(nonzero)



[3, 2, 5, 4, 4, 3, 2, 4, 3]


In [119]:
#print(nonzero)
max(nonzero)
k1 = nonzero.index(max(nonzero))
thisdict = {0: [0,0], 1:[0,3], 2:[0,6], 3:[3,0], 4:[3,3], 5:[3,6], 6:[6,0], 7:[6,3], 8:[6,6]}
#thisdict[k1] = [0,6]

#tlc = thisdict[k1] #tlc = topleftcorner of the box with the maximum number of non-zero digits

solveblock(k1) ## easiest to start with the block that has the most number of given digits among all the blocks in the puzzle


for iteratn in range(itnum):
    #print('###iteration number', iteratn)
    for i in range(9):    ### the algorithm is run for each block (of the 9) of the puzzle.
        solveblock(i)

print('Solution:')
print(inp1)

Solution:
[[4 9 6 8 2 3 7 5 1]
 [2 1 8 7 5 4 6 9 3]
 [7 5 3 1 6 9 4 8 2]
 [5 3 1 9 4 8 2 7 6]
 [8 2 7 6 3 1 9 4 5]
 [6 4 9 2 7 5 1 3 8]
 [1 8 5 4 9 2 3 6 7]
 [3 7 4 5 1 6 8 2 9]
 [9 6 2 3 8 7 5 1 4]]


In [120]:
def solveblock(blockind):

    tlc = thisdict[blockind]
    inbox = [] # lists all the numbers in the box 
    noind = [] #lists array indices where there is 0
    for i in range(3):
        for j in range(3): 
            #print(inp1[tlc[0]+i][tlc[1]+j]) # lists all the numbers in the box 
            
            if inp1[tlc[0]+i][tlc[1]+j] == 0:
                #print(tlc[0]+i, tlc[1]+j) #lists array indices where there is 0
                noind.append([tlc[0]+i, tlc[1]+j])
            else:
                inbox.append(inp1[tlc[0]+i][tlc[1]+j]) #lists numbers that are present in the box
    
    
    r = [i for i in range(1,10)]
    
    notinbox = [x for x in r if x not in inbox] # -- numbers that are not present in the box
    notinbox = np.array(notinbox)
    
    
    poss = []  # list of possibile numbers at each empty cell in the block
    #### the possibilities for a cell is determined by checking the row and column to which the cell belongs ###
    for i in noind:
        posst = []
        
        for j in notinbox:
            
            if j not in inp1[i[0]] and j not in inp1[:,i[1]]:

                posst.append(j)
        poss.append(posst)
        

    # noind -- indices where empty/0 places; first row (left to right), then column
    # notinbox -- numbers that are not present in the box
    # poss -- possibilities for each index/cell
    # noind --- poss ; ie. they map to each other
    
    rem = [] # solutions we are going to find in the next step
    remind = [] #indices/cells whose solutions we are going to find in the next step
    
    ### METHOD 1 to find solution: if there is only one value a cell can accept, then that value is the solution for the cell
    
    for i in range(len(poss)):
        
        if len(poss[i]) == 1:
            
            inp1[noind[i][0]][noind[i][1]] = poss[i][0]  # replaces the empty cell with the number
            rem.append(poss[i][0]) 
            remind.append(noind[i])
   
    notinbox1 = [x for x in notinbox if x not in rem] # --- updated the numbers that are not present in the box
       
    noind1 = [x for x in noind if x not in remind] # ---- updated the cells that are empty
       

    ##### check possibilities for the updated cells ####
    poss1 = []  # list of possibilities for each of the empty boxes
    for i in noind1:
        posst = []
        
        for j in notinbox1:
            
            if j not in inp1[i[0]] and j not in inp1[:,i[1]]:
                
                posst.append(j)
        poss1.append(posst)
        

    ### noind1 -- updated empty cells
    ### notinbox1 -- updated numbers that are not present in the box
    ### poss1 -- updated possibilities for each cell
    

    ### check using the only possibility method
    ### first count the number of times a possible number for empty cells occurs in the list of possibilities for each cell

    
    ### METHOD 2 : checks for numbers that can only occur in one cell in the block
    
    freq1 = [] ### possible numbers that occur only once
    for j in notinbox1:
        k = sum(x.count(j) for x in poss1)
        if k == 1:
            freq1.append(j)
    

    freq1ind = [] ### indices where those only-once occuring numbers are
    for i in freq1:
        for j in range(len(poss1)):
            if i in poss1[j]:
                freq1ind.append(noind1[j])

    #print(freq1ind) ### 
    ### freq1 maps with freqind1            

    for i in range(len(freq1)):
        inp1[freq1ind[i][0]][freq1ind[i][1]] = freq1[i]  ### replace the cells

    #print(inp1)
    ## This finishes the iteration for this block.
